esphome:
  name: tuyamcu
  friendly_name: TuyaMCU 
  on_boot:
    then:
      - delay: 5s
      # 1. Wake up the device (V0 Handshake)
      - script.execute: tasmota_fix
      - select.set:
          id: temp_unit
          option: "Celsius"

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: 
  reboot_timeout: 0s
  services:
    - service: force_unlock
      then:
        - script.execute: tasmota_fix

ota:
  - platform: esphome
    password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: 
    password: 

captive_portal:

web_server:
  port: 80

# ----------------------------------------------------------------
# 1. HARDWARE UART
# ----------------------------------------------------------------
uart:
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  rx_buffer_size: 2048

# ----------------------------------------------------------------
# 2. GLOBAL BUFFER
# ----------------------------------------------------------------
globals:
  - id: uart_buffer
    type: std::vector<uint8_t>
    restore_value: no

# ----------------------------------------------------------------
# 3. CUSTOM DRIVER LOGIC
# ----------------------------------------------------------------
interval:
  # --- PART A: THE PARSER (Reads bytes and updates sensors) ---
  - interval: 50ms
    then:
      - lambda: |
          // 1. Read bytes into buffer
          uint8_t c;
          while (id(uart_bus).available()) {
            if (id(uart_bus).read_byte(&c)) {
              id(uart_buffer).push_back(c);
            }
          }

          // 2. Process packets
          while (id(uart_buffer).size() >= 7) {
            // Check Header (55 AA)
            if (id(uart_buffer)[0] != 0x55 || id(uart_buffer)[1] != 0xAA) {
              id(uart_buffer).erase(id(uart_buffer).begin());
              continue;
            }

            // Get Length
            int len = (id(uart_buffer)[4] << 8) | id(uart_buffer)[5];
            int total_len = 6 + len + 1; // Header + Data + Checksum

            // Wait for full packet
            if (id(uart_buffer).size() < total_len) break; 

            // 3. Parse Data (Only Command 0x07 - Status Report)
            if (id(uart_buffer)[3] == 0x07) {
              int pos = 6;
              int end = total_len - 1;

              while (pos < end) {
                uint8_t dp_id = id(uart_buffer)[pos];
                // uint8_t dp_type = id(uart_buffer)[pos+1];
                int dp_len = (id(uart_buffer)[pos+2] << 8) | id(uart_buffer)[pos+3];
                int val_idx = pos + 4;

                if (val_idx + dp_len > end) break;

                // Extract Value
                int value = 0;
                if (dp_len == 1) {
                  value = id(uart_buffer)[val_idx];
                } else if (dp_len == 4) {
                  value = (id(uart_buffer)[val_idx] << 24) | 
                          (id(uart_buffer)[val_idx+1] << 16) | 
                          (id(uart_buffer)[val_idx+2] << 8) | 
                          id(uart_buffer)[val_idx+3];
                }

                // --- UPDATE SENSORS ---
                // DP 1: Power
                if (dp_id == 1) id(power_switch).publish_state(value == 1);
                
                // DP 2: Target Temp
                if (dp_id == 2) id(target_temp).publish_state(value);
                
                // DP 3: Current Temp
                if (dp_id == 3) id(current_temp).publish_state(value);
                
                // DP 4: Mode (0=High, 1=Low, 2=Eco)
                if (dp_id == 4) {
                  if (value == 0) id(mode_select).publish_state("High");
                  if (value == 1) id(mode_select).publish_state("Low");
                  if (value == 2) id(mode_select).publish_state("Eco");
                }

                // DP 7: Child Lock (Standard: 1=On)
                if (dp_id == 7) id(child_lock).publish_state(value == 1);

                // DP 101: Screen (Inverted: 1=Off, 0=On)
                if (dp_id == 101) id(screen_display).publish_state(value == 0);

                // DP 103: Sound/Beep (Inverted: 1=Off, 0=On)
                if (dp_id == 103) id(sound_beep).publish_state(value == 0);

                pos += 4 + dp_len;
              }
            }

            // Remove processed packet
            id(uart_buffer).erase(id(uart_buffer).begin(), id(uart_buffer).begin() + total_len);
          }

  # --- PART B: THE POLL LOOP (Keeps data flowing) ---
  - interval: 10s
    then:
      - script.execute: poll_data

# ----------------------------------------------------------------
# 4. CONTROLS
# ----------------------------------------------------------------
sensor:
  - platform: template
    name: "Thermostat Current Temp"
    id: current_temp

number:
  - platform: template
    name: "Thermostat Target Temp"
    id: target_temp
    min_value: 5
    max_value: 35
    step: 1
    optimistic: true
    set_action:
      - lambda: |
          int val = (int)x;
          // DP 2 Write (Integer)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x08, 0x02, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, (uint8_t)val};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

select:
  - platform: template
    name: "Thermostat Mode"
    id: mode_select
    optimistic: true
    options: ["High", "Low", "Eco"]
    set_action:
      - lambda: |
          // DP 4 Write (Enum)
          int val = 0; // Default High
          if (x == "High") val = 0;
          if (x == "Low") val = 1;
          if (x == "Eco") val = 2;
          
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x04, 0x04, 0x00, 0x01, (uint8_t)val};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

  - platform: template
    name: "Thermostat Unit"
    id: temp_unit
    optimistic: true
    options: ["Celsius", "Fahrenheit"]
    set_action:
      - lambda: |
          // DP 103 Write (Enum) - assuming 103 is Unit
          int val = (x == "Fahrenheit") ? 1 : 0;
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 103, 0x04, 0x00, 0x01, (uint8_t)val};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

switch:
  - platform: template
    name: "Thermostat Power"
    id: power_switch
    optimistic: true
    turn_on_action:
      - lambda: |
          // DP 1 ON (1)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x01, 0x01, 0x00, 0x01, 0x01};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());
    turn_off_action:
      - lambda: |
          // DP 1 OFF (0)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x01, 0x01, 0x00, 0x01, 0x00};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

  - platform: template
    name: "Child Lock"
    id: child_lock
    icon: "mdi:lock"
    optimistic: true
    turn_on_action:
      - lambda: |
          // DP 7 ON (1)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x07, 0x01, 0x00, 0x01, 0x01};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());
    turn_off_action:
      - lambda: |
          // DP 7 OFF (0)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x07, 0x01, 0x00, 0x01, 0x00};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

  - platform: template
    name: "Screen Display"
    id: screen_display
    icon: "mdi:monitor"
    optimistic: true
    turn_on_action:
      - lambda: |
          // DP 101 ON (Value 0)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 101, 0x01, 0x00, 0x01, 0x00};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());
    turn_off_action:
      - lambda: |
          // DP 101 OFF (Value 1)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 101, 0x01, 0x00, 0x01, 0x01};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

  - platform: template
    name: "Silent Mode (Beep)"
    id: sound_beep
    icon: "mdi:volume-high"
    optimistic: true
    turn_on_action:
      - lambda: |
          // DP 103 ON/Sound (Value 0)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 103, 0x01, 0x00, 0x01, 0x00};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());
    turn_off_action:
      - lambda: |
          // DP 103 OFF/Silent (Value 1)
          std::vector<uint8_t> cmd = {0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 103, 0x01, 0x00, 0x01, 0x01};
          uint8_t cs = 0; for(int i=0; i<cmd.size(); i++) cs += cmd[i]; cmd.push_back(cs);
          id(uart_bus).write_array(cmd.data(), cmd.size());

# ----------------------------------------------------------------
# 5. SCRIPTS
# ----------------------------------------------------------------
script:
  - id: tasmota_fix
    then:
      - lambda: |
          std::vector<uint8_t> step1 = {0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07};
          id(uart_bus).write_array(step1.data(), step1.size());
      - delay: 300ms
      - lambda: |
          std::vector<uint8_t> step2 = {0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x02, 0x05};
          id(uart_bus).write_array(step2.data(), step2.size());
      - delay: 300ms
      - lambda: |
          std::vector<uint8_t> step3 = {0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x03, 0x06};
          id(uart_bus).write_array(step3.data(), step3.size());
      - delay: 300ms
      - lambda: |
          std::vector<uint8_t> final_q = {0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07};
          id(uart_bus).write_array(final_q.data(), final_q.size());

  - id: poll_data
    then:
      - lambda: |
          std::vector<uint8_t> poll = {0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07};
          id(uart_bus).write_array(poll.data(), poll.size());